# Generated by Django 2.1.5 on 2019-07-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrollment',
            field=models.CharField(default='111X111', max_length=10),
        ),
    ]
