# Generated by Django 2.1.5 on 2019-08-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_messagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
