# Generated by Django 2.1.5 on 2019-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190823_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='reciever',
            field=models.IntegerField(),
        ),
    ]
