# Generated by Django 2.1.5 on 2019-08-23 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190823_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
