# Generated by Django 2.1.5 on 2019-08-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_messagedata_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagedata',
            old_name='reciever',
            new_name='recieverID',
        ),
    ]
