# Generated by Django 2.1.5 on 2019-08-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190823_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='senderName',
            field=models.CharField(default='Roshan', max_length=100),
            preserve_default=False,
        ),
    ]
