# Generated by Django 2.1.5 on 2019-08-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_messagedata_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
