# Generated by Django 2.1.5 on 2019-08-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190826_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='messageText',
            field=models.TextField(),
        ),
    ]
