# Generated by Django 2.1.5 on 2019-08-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190827_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='messageText',
            field=models.CharField(max_length=1000),
        ),
    ]
