# Generated by Django 2.1.5 on 2019-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190828_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friendName',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
