# Generated by Django 2.1.5 on 2019-08-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notifications_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friendName',
        ),
    ]
