# Generated by Django 2.1.5 on 2019-09-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_friends_friendname'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='myFollowers',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
