# Generated by Django 2.1.5 on 2019-09-10 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_auto_20190910_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendTable',
            new_name='Fdata',
        ),
        migrations.AlterModelOptions(
            name='fdata',
            options={'verbose_name': 'Authentic Friend', 'verbose_name_plural': 'Authentic Friend'},
        ),
    ]
