# Generated by Django 2.1.5 on 2019-09-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0026_auto_20190910_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utem', to=settings.AUTH_USER_MODEL),
        ),
    ]
