# Generated by Django 2.1.5 on 2019-09-10 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0027_auto_20190910_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdata',
            name='friends',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='fdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
