# Generated by Django 2.1.5 on 2019-09-10 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0028_auto_20190910_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fdata',
            new_name='Following',
        ),
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name': 'Following', 'verbose_name_plural': 'Following'},
        ),
    ]
