# Generated by Django 2.1.5 on 2019-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='OTP',
            field=models.IntegerField(default=111111),
        ),
        migrations.AddField(
            model_name='profile',
            name='varifiedProfile',
            field=models.BooleanField(default=False),
        ),
    ]
