# Generated by Django 2.1.5 on 2019-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20190912_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default=1212121212),
        ),
        migrations.AlterField(
            model_name='profile',
            name='OTP',
            field=models.IntegerField(default=120391),
        ),
    ]
