# Generated by Django 2.1.5 on 2019-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20190913_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebookHandle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='githubHandle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedinHandle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='OTP',
            field=models.IntegerField(default=498314),
        ),
    ]
