# Generated by Django 2.1.5 on 2019-09-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20190913_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='OTP',
            field=models.IntegerField(default=614377),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='CSE', max_length=100, verbose_name='Area of Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebookHandle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Facebook Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='githubHandle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Github Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedinHandle',
            field=models.CharField(blank=True, max_length=150, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default=1212121212, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Portfolio'),
        ),
    ]
