# Generated by Django 2.1.5 on 2019-09-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20190913_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='branch',
            new_name='areaOfInterest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='enrollment',
        ),
        migrations.AlterField(
            model_name='profile',
            name='OTP',
            field=models.IntegerField(default=571249),
        ),
    ]
