# Generated by Django 2.1.5 on 2019-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_likeonpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeonpost',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
