# Generated by Django 2.1.5 on 2019-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likeonpost_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeonpost',
            name='likeCount',
            field=models.BooleanField(),
        ),
    ]
