# Generated by Django 2.1.5 on 2019-08-22 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20190822_1536'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeonpost',
            unique_together={('user', 'post')},
        ),
    ]
