# Generated by Django 2.1.5 on 2019-08-23 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_reviewsdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsdata',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
