# Generated by Django 2.1.5 on 2019-08-26 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190823_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeonpost',
            name='likeCount',
            field=models.BooleanField(verbose_name='Liked'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Writer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Views on Post'),
        ),
        migrations.AlterField(
            model_name='reviewsdata',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='reviewsdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Writer'),
        ),
    ]
