# Generated by Django 2.1.5 on 2019-08-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190826_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeonpost',
            options={'verbose_name': 'Likes', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='reviewsdata',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
    ]
