# Generated by Django 2.1.5 on 2019-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190828_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewersIDs',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
