# Generated by Django 2.1.5 on 2019-08-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_viewersids'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uniqueCount',
            field=models.IntegerField(default=1, verbose_name='Unique Count'),
        ),
    ]
