# Generated by Django 2.1.5 on 2019-09-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_uniquecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Mark if Passes Community Guidelines'),
        ),
    ]
