# Generated by Django 2.1.5 on 2019-09-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportedPostID', models.IntegerField()),
                ('reportedByUser', models.IntegerField()),
            ],
        ),
    ]
