# Generated by Django 2.1.5 on 2019-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_reportpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportpost',
            options={'verbose_name': 'Reprted Post', 'verbose_name_plural': 'Reprted Post'},
        ),
        migrations.AddField(
            model_name='reportpost',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
