# Generated by Django 2.1.5 on 2019-09-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190905_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportpost',
            options={'verbose_name': 'Reported Post', 'verbose_name_plural': 'Reported Post'},
        ),
        migrations.AddField(
            model_name='reportpost',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reportedByUser',
            field=models.IntegerField(verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reportedPostID',
            field=models.IntegerField(verbose_name='Post ID'),
        ),
    ]
