# Generated by Django 2.1.5 on 2019-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190905_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Mark as read'),
        ),
    ]
