# Generated by Django 2.1.5 on 2019-09-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190905_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='skills',
        ),
        migrations.DeleteModel(
            name='skillSet',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
