# Generated by Django 2.1.5 on 2019-09-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190905_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeonpost',
            name='users',
        ),
    ]
