# Generated by Django 2.1.5 on 2019-09-05 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_remove_likeonpost_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeonpost',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
