# Generated by Django 2.1.5 on 2019-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_likeonpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Likes',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
