# Generated by Django 2.1.5 on 2019-09-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeonpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likeonpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikeOnPost',
        ),
    ]
