# Generated by Django 2.1.5 on 2019-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190906_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Hates',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
